services:
  - type: web
    name: iris-streamlit
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.enableCORS falsegit add render.yaml
